rss_links = [
	# New 3-26-2016
	{'source': 'bundesliga365', 'category': 'sport', 'sub_category': [''], 'link': 'http://www.bundesliga365.com/feed/'},
	{'source': 'DW', 'category': 'business', 'sub_category': [''], 'link': 'http://rss.dw.de/rdf/rss-en-bus'},
	{'source': 'DW', 'category': 'lifestyle', 'sub_category': [''], 'link': 'http://rss.dw.de/rdf/rss-en-cul'},
	{'source': 'DW', 'category': 'sport', 'sub_category': [''], 'link': 'http://rss.dw.de/rdf/rss-en-sports'},
	{'source': 'DW', 'category': 'world', 'sub_category': [''], 'link': 'http://rss.dw.de/rdf/rss-en-world'},
	
	{'source': 'Spiegel', 'category': 'international', 'sub_category': [''], 'link': 'http://www.spiegel.de/international/index.rss'},
	{'source': 'Spiegel', 'category': 'germany', 'sub_category': [''], 'link': 'http://www.spiegel.de/international/germany/index.rss'},
	{'source': 'Spiegel', 'category': 'european', 'sub_category': [''], 'link': 'http://www.spiegel.de/international/europe/index.rss'},
	{'source': 'Spiegel', 'category': 'world', 'sub_category': [''], 'link': 'http://www.spiegel.de/international/world/index.rss'},
	{'source': 'Spiegel', 'category': 'business', 'sub_category': [''], 'link': 'http://www.spiegel.de/international/business/index.rss'},
	
	{'source': 'thelocal', 'category': 'international', 'sub_category': [''], 'link': 'http://www.thelocal.ch/feeds/rss.php'},
	
	{'source': 'friedlnews', 'category': 'health', 'sub_category': [''], 'link': 'http://www.friedlnews.com/rss/health-pharmaceuticals'},
	{'source': 'friedlnews', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.friedlnews.com/rss/opinion'},
	{'source': 'friedlnews', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.friedlnews.com/rss/politics-policy'},
	{'source': 'friedlnews', 'category': 'tech', 'sub_category': [''], 'link': 'http://www.friedlnews.com/rss/technology'},
	{'source': 'friedlnews', 'category': 'business', 'sub_category': [''], 'link': 'http://www.friedlnews.com/rss/economy'},
	
	{'source': 'viennareview', 'category': 'world', 'sub_category': [''], 'link': 'http://www.viennareview.net/category/news/feed'},
	
	{'source': 'bangkokpost', 'category': 'Most recent', 'sub_category': [''], 'link': 'http://www.bangkokpost.com/rss/data/most-recent.xml'},
	{'source': 'bangkokpost', 'category': 'Top stories', 'sub_category': [''], 'link': 'http://www.bangkokpost.com/rss/data/topstories.xml'},
	{'source': 'bangkokpost', 'category': 'News', 'sub_category': [''], 'link': 'http://www.bangkokpost.com/rss/data/news.xml'},
	{'source': 'bangkokpost', 'category': 'Business', 'sub_category': [''], 'link': 'http://www.bangkokpost.com/rss/data/business.xml'},
	{'source': 'bangkokpost', 'category': 'Opinion', 'sub_category': [''], 'link': 'http://www.bangkokpost.com/rss/data/opinion.xml'},
	{'source': 'bangkokpost', 'category': 'Learning', 'sub_category': [''], 'link': 'http://www.bangkokpost.com/rss/data/learning.xml'},
	{'source': 'bangkokpost', 'category': 'Tech', 'sub_category': [''], 'link': 'http://www.bangkokpost.com/rss/data/tect.xml'},
	{'source': 'bangkokpost', 'category': 'Lifestyle', 'sub_category': [''], 'link': 'http://www.bangkokpost.com/rss/data/life.xml'},
	{'source': 'bangkokpost', 'category': 'Travel', 'sub_category': [''], 'link': 'http://www.bangkokpost.com/rss/data/travel.xml'},
	
	# New 4-2-2016
	{'source': 'nationmultimedia', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.nationmultimedia.com/home/rss/breakingnews.rss'},
	{'source': 'nationmultimedia', 'category': 'business', 'sub_category': [''], 'link': 'http://www.nationmultimedia.com/home/rss/business.rss'},
	{'source': 'nationmultimedia', 'category': 'lifestyle', 'sub_category': [''], 'link': 'http://www.nationmultimedia.com/home/rss/life.rss'},
	{'source': 'nationmultimedia', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.nationmultimedia.com/home/rss/mekong.rss'},
	{'source': 'nationmultimedia', 'category': 'opinion', 'sub_category': [''], 'link': 'http://www.nationmultimedia.com/home/rss/opinion.rss'},
	{'source': 'nationmultimedia', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.nationmultimedia.com/home/rss/politics.rss'},
	{'source': 'nationmultimedia', 'category': 'sports', 'sub_category': [''], 'link': 'http://www.nationmultimedia.com/home/rss/sports.rss'},
	{'source': 'nationmultimedia', 'category': 'tech', 'sub_category': [''], 'link': 'http://www.nationmultimedia.com/home/rss/technology.rss'},
	{'source': 'nationmultimedia', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.nationmultimedia.com/home/rss/topstories.rss'},
	{'source': 'nationmultimedia', 'category': 'travel', 'sub_category': [''], 'link': 'http://www.nationmultimedia.com/home/rss/travel.rss'},

	{'source': 'geo', 'category': 'health', 'sub_category': [''], 'link': 'http://feeds.feedburner.com/GeoHealth-GeoTvNetwork'},
	{'source': 'geo', 'category': 'world', 'sub_category': [''], 'link': 'http://feeds.feedburner.com/geo/wUIl'},
	{'source': 'geo', 'category': 'science', 'sub_category': [''], 'link': 'http://jang.net/tp_db_agg/jangfeeds/Education-News.xml'},
	{'source': 'geo', 'category': 'world', 'sub_category': [''], 'link': 'http://jang.net/tp_db_agg/jangfeeds/USA-News.xml'},

	{'source': 'TheNewsInternational', 'category': 'opinion', 'sub_category': [''], 'link': 'http://feeds.feedburner.com/TheNewsInternational-Editorial	'},
	{'source': 'TheNewsInternational', 'category': 'politics', 'sub_category': [''], 'link': 'http://feeds.feedburner.com/TheNewsInternational-Karachi'},
	{'source': 'TheNewsInternational', 'category': 'politics', 'sub_category': [''], 'link': 'http://feeds.feedburner.com/TheNewsInternational-Lahore	'},
	{'source': 'TheNewsInternational', 'category': 'politics', 'sub_category': [''], 'link': 'http://feeds.feedburner.com/TheNewsInternational-National'},
	{'source': 'TheNewsInternational', 'category': 'opinion', 'sub_category': [''], 'link': 'http://feeds.feedburner.com/TheNewsInternational-Newspost'},
	{'source': 'TheNewsInternational', 'category': 'opinion', 'sub_category': [''], 'link': 'http://feeds.feedburner.com/TheNewsInternational-Opinion'},
	{'source': 'TheNewsInternational', 'category': 'politics', 'sub_category': [''], 'link': 'http://feeds.feedburner.com/TheNewsInternational-Peshawar'},
	{'source': 'TheNewsInternational', 'category': 'world', 'sub_category': [''], 'link': 'http://feeds.feedburner.com/World-TheNewsInternational'},
	{'source': 'TheNewsInternational', 'category': 'politics', 'sub_category': [''], 'link': 'http://feeds.feedburner.com/com/cwEr'},

	{'source': 'TheConnexion', 'category': 'news', 'sub_category': [''], 'link': 'http://www.connexionfrance.com/news.xml'},
	{'source': 'TheConnexion', 'category': 'business', 'sub_category': [''], 'link': 'http://www.connexionfrance.com/cnx_business.xml'},
	{'source': 'TheConnexion', 'category': 'healthcare', 'sub_category': [''], 'link': 'http://www.connexionfrance.com/cnx_healthcare.xml'},
	{'source': 'TheConnexion', 'category': 'money', 'sub_category': [''], 'link': 'http://www.connexionfrance.com/cnx_money.xml'},
	{'source': 'TheConnexion', 'category': 'practical', 'sub_category': [''], 'link': 'http://www.connexionfrance.com/cnx_practical.xml'},
	{'source': 'TheConnexion', 'category': 'americanconnexion', 'sub_category': [''], 'link': 'http://www.connexionfrance.com/cnx_american_conneexion.xml'},
	{'source': 'TheConnexion', 'category': 'letters', 'sub_category': [''], 'link': 'http://www.connexionfrance.com/cnx_letters.xml'},
	{'source': 'TheConnexion', 'category': 'community', 'sub_category': [''], 'link': 'http://www.connexionfrance.com/cnx_community.xml'},
	{'source': 'TheConnexion', 'category': 'property', 'sub_category': [''], 'link': 'http://www.connexionfrance.com/cnx_property.xml'},
	
	# New 4-14-2016
	{'source': 'asiaone', 'category': 'world', 'sub_category': [''], 'link': 'http://asiaone.feedsportal.com/c/34151/f/618416/index.rss'},
	{'source': 'asiaone', 'category': 'world', 'sub_category': [''], 'link': 'http://asiaone.feedsportal.com/c/34151/f/618417/index.rss'},
	{'source': 'asiaone', 'category': 'sports', 'sub_category': [''], 'link': 'http://asiaone.feedsportal.com/c/34151/f/618420/index.rss'},
	{'source': 'asiaone', 'category': 'science', 'sub_category': [''], 'link': 'http://asiaone.feedsportal.com/c/34151/f/618421/index.rss'},
	
	{'source': 'channelnewsasia', 'category': 'world', 'sub_category': [''], 'link': 'http://www.channelnewsasia.com/starterkit/servlet/cna/rss/asiapacific.xml'},
	{'source': 'channelnewsasia', 'category': 'business', 'sub_category': [''], 'link': 'http://www.channelnewsasia.com/starterkit/servlet/cna/rss/business.xml'},
	{'source': 'channelnewsasia', 'category': 'sports', 'sub_category': [''], 'link': 'http://www.channelnewsasia.com/starterkit/servlet/cna/rss/sport.xml'},
	{'source': 'channelnewsasia', 'category': 'world', 'sub_category': [''], 'link': 'http://www.channelnewsasia.com/starterkit/servlet/cna/rss/world.xml'},
	
	{'source': 'todayonline', 'category': 'business', 'sub_category': [''], 'link': 'http://www.todayonline.com/feed/business'},
	{'source': 'todayonline', 'category': 'entertainment', 'sub_category': [''], 'link': 'http://www.todayonline.com/feed/entertainment'},
	{'source': 'todayonline', 'category': 'lifestyle', 'sub_category': [''], 'link': 'http://www.todayonline.com/feed/lifestyle'},
	{'source': 'todayonline', 'category': 'world', 'sub_category': [''], 'link': 'http://www.todayonline.com/feed/singapore'},
	{'source': 'todayonline', 'category': 'sports', 'sub_category': [''], 'link': 'http://www.todayonline.com/feed/sports'},
	{'source': 'todayonline', 'category': 'tech', 'sub_category': [''], 'link': 'http://www.todayonline.com/feed/tech'},
	{'source': 'todayonline', 'category': 'world', 'sub_category': [''], 'link': 'http://www.todayonline.com/feed/world'},

	{'source': 'bellanaija', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.bellanaija.com/feed/'},

	{'source': 'nigeria-news-world', 'category': 'politics', 'sub_category': [''], 'link': 'http://feeds.feedburner.com/NigeriaWorldNews'},
	
	{'source': 'punchng', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.punchng.com/feed/'},

	{'source': 'rian', 'category': 'politics', 'sub_category': [''], 'link': 'http://rss.feedsportal.com/c/860/fe.ed/en.rian.ru/export/rss2/archive/index.xml'},
	{'source': 'rian', 'category': 'business', 'sub_category': [''], 'link': 'http://rss.feedsportal.com/c/860/fe.ed/en.rian.ru/export/rss2/business/index.xml'},
	{'source': 'rian', 'category': 'lifestyle', 'sub_category': [''], 'link': 'http://rss.feedsportal.com/c/860/fe.ed/en.rian.ru/export/rss2/culture/index.xml'},
	{'source': 'rian', 'category': 'politics', 'sub_category': [''], 'link': 'http://rss.feedsportal.com/c/860/fe.ed/en.rian.ru/export/rss2/russia/index.xml'},
	{'source': 'rian', 'category': 'tech', 'sub_category': [''], 'link': 'http://rss.feedsportal.com/c/860/fe.ed/en.rian.ru/export/rss2/science/index.xml'},
	{'source': 'rian', 'category': 'lifestyle', 'sub_category': [''], 'link': 'http://rss.feedsportal.com/c/860/fe.ed/en.rian.ru/export/rss2/society/index.xml'},
	{'source': 'rian', 'category': 'sports', 'sub_category': [''], 'link': 'http://rss.feedsportal.com/c/860/fe.ed/en.rian.ru/export/rss2/sports/index.xml'},
	{'source': 'rian', 'category': 'world', 'sub_category': [''], 'link': 'http://rss.feedsportal.com/c/860/fe.ed/en.rian.ru/export/rss2/strange/index.xml	'},
	{'source': 'rian', 'category': 'world', 'sub_category': [''], 'link': 'http://rss.feedsportal.com/c/860/fe.ed/en.rian.ru/export/rss2/world/index.xml'},

	{'source': 'upi', 'category': 'tech', 'sub_category': [''], 'link': 'http://rss.upi.com/news/bn_si.rss'},
	{'source': 'upi', 'category': 'business', 'sub_category': [''], 'link': 'http://rss.upi.com/news/business_news.rss'},
	{'source': 'upi', 'category': 'politics', 'sub_category': [''], 'link': 'http://rss.upi.com/news/emerging_threats.rss'},
	{'source': 'upi', 'category': 'entertainment', 'sub_category': [''], 'link': 'http://rss.upi.com/news/entertainment_news.rss	'},
	{'source': 'upi', 'category': 'health', 'sub_category': [''], 'link': 'http://rss.upi.com/news/health_news.rss	'},
	{'source': 'upi', 'category': 'politics', 'sub_category': [''], 'link': 'http://rss.upi.com/news/news.rss'},
	{'source': 'upi', 'category': 'politics', 'sub_category': [''], 'link': 'http://rss.upi.com/news/newstrack.rss'},
	{'source': 'upi', 'category': 'world', 'sub_category': [''], 'link': 'http://rss.upi.com/news/odd_news.rss'},
	{'source': 'upi', 'category': 'science', 'sub_category': [''], 'link': 'http://rss.upi.com/news/science_news.rss'},
	{'source': 'upi', 'category': 'science', 'sub_category': [''], 'link': 'http://rss.upi.com/news/sn_rw.rss'},
	{'source': 'upi', 'category': 'sports', 'sub_category': [''], 'link': 'http://rss.upi.com/news/sports_news.rss	'},
	{'source': 'upi', 'category': 'politics', 'sub_category': [''], 'link': 'http://rss.upi.com/news/top_news.rss'},

	{'source': 'calgarysun', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.calgarysun.com/home/rss.xml'},
	{'source': 'calgarysun', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.calgarysun.com/news/alberta/rss.xml	'},
	{'source': 'calgarysun', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.calgarysun.com/news/calgary/rss.xml'},
	{'source': 'calgarysun', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.calgarysun.com/news/canada/rss.xml'},
	{'source': 'calgarysun', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.calgarysun.com/news/rss.xml'},
	{'source': 'calgarysun', 'category': 'world', 'sub_category': [''], 'link': 'http://www.calgarysun.com/news/weird/rss.xml'},
	{'source': 'calgarysun', 'category': 'world', 'sub_category': [''], 'link': 'http://www.calgarysun.com/news/world/rss.xml'},

	{'source': 'cbc', 'category': 'entertainment', 'sub_category': [''], 'link': 'http://rss.cbc.ca/lineup/arts.xml'},
	{'source': 'cbc', 'category': 'business', 'sub_category': [''], 'link': 'http://rss.cbc.ca/lineup/business.xml'},
	{'source': 'cbc', 'category': 'politics', 'sub_category': [''], 'link': 'http://rss.cbc.ca/lineup/canada.xml	'},
	{'source': 'cbc', 'category': 'health', 'sub_category': [''], 'link': 'http://rss.cbc.ca/lineup/health.xml	'},
	{'source': 'cbc', 'category': 'lifestyle', 'sub_category': [''], 'link': 'http://rss.cbc.ca/lineup/offbeat.xml	'},
	{'source': 'cbc', 'category': 'politics', 'sub_category': [''], 'link': 'http://rss.cbc.ca/lineup/politics.xml'},
	{'source': 'cbc', 'category': 'sports', 'sub_category': [''], 'link': 'http://rss.cbc.ca/lineup/sports.xml	'},
	{'source': 'cbc', 'category': 'tech', 'sub_category': [''], 'link': 'http://rss.cbc.ca/lineup/technology.xml	'},
	{'source': 'cbc', 'category': 'world', 'sub_category': [''], 'link': 'http://rss.cbc.ca/lineup/world.xml	'},

	
	{'source': 'thestar', 'category': 'business', 'sub_category': [''], 'link': 'http://www.thestar.com/feeds.articles.business.rss'},
	{'source': 'thestar', 'category': 'entertainment', 'sub_category': [''], 'link': 'http://www.thestar.com/feeds.articles.entertainment.rss'},
	{'source': 'thestar', 'category': 'business', 'sub_category': [''], 'link': 'http://www.thestar.com/feeds.articles.initiatives.fresh_air_fund.rss'},
	{'source': 'thestar', 'category': 'business', 'sub_category': [''], 'link': 'http://www.thestar.com/feeds.articles.initiatives.santa_claus_fund.rss	'},
	{'source': 'thestar', 'category': 'lifestyle', 'sub_category': [''], 'link': 'http://www.thestar.com/feeds.articles.life.rss	'},
	{'source': 'thestar', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.thestar.com/feeds.articles.news.rss'},
	{'source': 'thestar', 'category': 'opinion', 'sub_category': [''], 'link': 'http://www.thestar.com/feeds.articles.opinion.rss'},
	{'source': 'thestar', 'category': 'sports', 'sub_category': [''], 'link': 'http://www.thestar.com/feeds.articles.sports.rss'},
	{'source': 'thestar', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.thestar.com/feeds.articles.yourtoronto.rss	'},

	{'source': 'timescolonist', 'category': 'business', 'sub_category': [''], 'link': 'http://www.timescolonist.com/cmlink/business-rss-1.695'},
	{'source': 'timescolonist', 'category': 'entertainment', 'sub_category': [''], 'link': 'http://www.timescolonist.com/cmlink/entertainment-rss-1.719	'},
	{'source': 'timescolonist', 'category': 'lifestyle', 'sub_category': [''], 'link': 'http://www.timescolonist.com/cmlink/life-rss-1.755	'},
	{'source': 'timescolonist', 'category': 'politics', 'sub_category': [''], 'link': 'http://www.timescolonist.com/cmlink/news-rss-1.769	'},
	{'source': 'timescolonist', 'category': 'opinion', 'sub_category': [''], 'link': 'http://www.timescolonist.com/cmlink/opinion-rss-1.783	'},
	{'source': 'timescolonist', 'category': 'sports', 'sub_category': [''], 'link': 'http://www.timescolonist.com/cmlink/sports-rss-1.811'}
]
